# Generated by Django 5.1.1 on 2024-10-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituteapp', '0002_coursedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetails',
            name='trainer_name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
